name: Client CI/CD

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'client/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd client
          npm i
          npm ci
          npm run build
          git config user.name github-actions
          git config user.email github-actions@github.com
          git --work-tree build add --all
          git commit -m "Automatic Build and Deploy run by GitHub Actions"
          git push origin HEAD:gh-pages --force
