name: Client CI/CD

on: 
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths: 
      - 'client/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'client/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/pallass-gh-actions-role
          aws-region: us-east-1

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install
      working-directory: ./client 

    - name: Build React app
      run: npm run build-prod
      working-directory: ./client
      env:
        VITE_API_ENDPOINT: ${{ secrets.REACT_API_ENDPOINT }}

    - name: Deploy to GitHub Pages
      run: | 
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      working-directory: ./client
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
