name: Client CI/CD

on: 
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths: 
      - 'client/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'client/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install
      working-directory: ./client 

    - name: Build React app
      run: npm run build
      working-directory: ./client

    - name: Configure git for deployment
      run: |
        git config user.email "github-actions@github.com"
        git config user.name "github-actions"
      working-directory: ./client

    - name: Deploy to GitHub Pages
      run: | 
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      working-directory: ./client
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
