name: Client CI/CD

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'client/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'client/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install
      working-directory: ./client 

    - name: Build React app
      run: npm run build
      working-directory: ./client

    - name: Configure git for deployment
      run: |
        git config user.email ysheliakin@ufl.edu
        git config user.name "github-actions"
      working-directory: ./client

    - name: Deploy to GitHub Pages
      run: npm run deploy
      working-directory: ./client

    - name: Push to gh-pages branch
      run: git push origin `git subtree split --prefix client build`:gh-pages --force
